### ISSUE TITLE
Cannot get website to fit to screen

### ISSUE THREAD

**Issue by kieffer-reitenbach** [kieffer-reitenbach/type-those-grids#1]
The comparison in markbot shows that my website is way larger than the example.
Im assuming it's the min/max stuff but nothing was specified so theres no way of knowing what to do.
@hellachella
@anna-pokhilenko

**Comment by anna-pokhilenko** [comment]
Hello)
Just looked at your code and there are some tips to make it work:

1. Add `img {
  width: 100%;
}` to your css.
2. I spotted that in your **header** you have a **figure with an image**. I suggest you **put it in the main section**. You will have **an image called banner and a div with h2 and p** followed by all the figures. (Remove ul and li as well, you are good with figures only)
This way you will be able to spread the banner across three columns and assign each figure you have a column. It should look like that:
` main {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-areas:
  "banner banner banner"
  "col1 col2 col3";
}`
**Please note that the grid should be put in the main section because we want to leave the header alone so it would span across the page and wouldn't intersect with our grid.**
This should fix your issue.
The only thing that you will have to deal with is finding a way to put the text over the banner image.

**Comment by anna-pokhilenko** [comment]
Let me know if it worked for you!

**Comment by kieffer-reitenbach** [comment]
Thank you that helped alot!
I'm still having trouble with the cloumns though, Ive assigned them a role except i know there was some way of linking them but I'm nto sure how when they're all the same element?

**Comment by kieffer-reitenbach** [comment]
@anna-pokhilenko 
So I got the grids to work, I, m just struggling with the sizes again...

**Comment by anna-pokhilenko** [comment]
Hey! Just looked at your website and it looks fantastic! 
I'm glad you could figure it out)

If you don't need any help with this assignment, you can close the issue.
